defaults: &defaults
 
:development:
  :sqlite3:
    :adapter: sqlite3
    :database: db/development.sqlite3
    <<: *defaults

:test:
  :sqlite3:
    :database: db/test.sqlite3
    <<: *defaults

:production:
  :sqlite3:
    :database: db/production.sqlite3
    <<: *defaults
