defaults: &defaults
  :app_name:            flood_monkey
  # CHANGEME -- set your domain
  :domain:              yourdomain.com
  # CHANGEME -- point to your git repo
  :repository:          git://github.com/mrflip/flood_monkey.git

  # CHANGEME -- Choose the username and password that protect subscription calls
  :basic_auth:
    :username:            username_for_basic_auth
    :password:            password_for_basic_auth

  # Settings for myspace API calls
  :myspace:
    # CHANGEME -- set to the full url to your OAuth callback
    :oauth_callback_url:   http://yourdomain.com/endpoint/myspace/cb
    # CHANGEME -- Visit http://developer.myspace.com/Apps.mvc to find your keys
    :consumer_key:         your_myspace_consumer_key
    :consumer_secret:      your_myspace_consumer_secret
    :oauth_setup:
      :site:               http://api.myspace.com
      :request_token_path: /request_token
      :authorize_path:     /authorize
      :access_token_path:  /access_token
      :oauth_version:      1.0
      :scheme:             :header
      :http_method:        :get
 
:development:
  <<: *defaults
  :log_level:           info
  # CHANGEME -- mash on the keyboard or something
  :session_secret:      SOMETHINGLONGANDCOMPLICATED_1
  :sqlite3:
    :adapter: sqlite3
    :database: db/development.sqlite3

:test:
  <<: *defaults
  :log_level:           debug
  # CHANGEME -- mash on the keyboard or something
  :session_secret:      SOMETHINGLONGANDCOMPLICATED_2
  :sqlite3:
    :adapter: sqlite3
    :database: db/test.sqlite3

:production:
  <<: *defaults
  :log_level:           warn
  # CHANGEME -- mash on the keyboard or something
  :session_secret:      SOMETHINGLONGANDCOMPLICATED_3
  :sqlite3:
    :adapter: sqlite3
    :database: db/production.sqlite3
